### ISSUE TITLE
No longer on NPM registry

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/dirty-reprojectors#10]
I was going to use this for a project but discovered it's no longer on NPM :( We should publish it again.

**Comment by mike-marcacci** [comment]
I don't believe this is correct (perhaps npm was having issues):

https://www.npmjs.com/package/dirty-reprojectors

**Comment by dereklieu** [comment]
Ah, I re-published it so that explains why it's there now. Forgot to close this ticket. Sorry about that.
