### ISSUE TITLE
Using AlbersUsa on mapbox.gl, adding points on dirty projection

### ISSUE THREAD

**Issue by radames** [developmentseed/dirty-reprojectors#12]
Hi, 
Trying to use AbersUsa on mapbox.gl, following your hacked dirty-reprojector.

Just curious if I can converted the LatLgn back to mapbox.gl coordinates. Is there any specific offset to put points on the hacked projected map?
I've tried  using d3 projection to convert the LatLgn and unproject, both not successful. 

Could you please give me some workaround on how did you do that?

```js
const projection = d3.geoAlbersUsa();

const a = new mapboxgl.Marker()
  .setLngLat(map.unproject(projection([-122.2708026,37.8043722])))
  .addTo(map);

const b = new mapboxgl.Marker()
    .setLngLat([-122.2708026,37.8043722])
    .addTo(map);

```
<img width="1661" alt="a" src="https://user-images.githubusercontent.com/102277/39149926-8749536a-46f5-11e8-8f50-724b88332e25.png">

**Comment by dereklieu** [comment]
@radames the first approach seems like it should work if you [scale your projection accordingly](https://github.com/developmentseed/dirty-reprojectors/blob/master/projections/index.js#L119)

**Comment by dereklieu** [comment]
Actually I don't think you want to use `map.unproject` here as that will give you lng/lat relative to the container. You want to take a lng/lat, project it to albers at the correct scale, then project that back to web mercator I believe.

**Comment by radames** [comment]
@dereklieu thanks for the perfect tip! it amazing works! thanks
```js

let R = 6378137.0; // radius of Earth in meters
const projection = d3.geoAlbersUsa().translate([0, 0]).scale(R);
const projectionMercartor = d3.geoMercator().translate([0, 0]).scale(R);

const a = new mapboxgl.Marker()
  .setLngLat(projectionMercartor.invert(projection([-122.2708026,37.8043722])))
  .addTo(map);

```
<img width="1320" alt="screen shot 2018-04-23 at 13 53 19" src="https://user-images.githubusercontent.com/102277/39152596-b6cc4c16-46fd-11e8-9e48-253853897ed2.png">
