### ISSUE TITLE
Use `d3-geo-projection`

### ISSUE THREAD

**Issue by anandthakker** [developmentseed/dirty-reprojectors#5]
I noticed in a tweet by mbostock this weekend that `d3-geo-projection` actually ships with [command line tools](https://github.com/d3/d3-geo-projection#command-line-reference) which might obviate some of the work that's happening in `reproject-geojson`.   I think it would make sense to refactor to use that, and keep this repository very specifically focused on the trickery required to get this to work with Mapbox Studio / GL

**Comment by dereklieu** [comment]
Yeah, I basically discovered that around the same time and am working on that in this [more projections branch](https://github.com/developmentseed/dirty-reprojectors/tree/more-projections). 

One issue I ran into early on is that all the projections come of the box with a flipped Y axis. I'm betting this is to make it plug-and-play with the D3/SVG workflow, which flips the Y axis as well. I made forks of `d3-geo` and `d3-geo-projection` to correct this, and it's working for everything *except* the all-important Albers US projection, which shows Hawai'i and Alaska right, but the continental 48 upside-down. This was as far as I got last weekend.

<img width="1145" alt="screen shot 2016-11-21 at 7 25 21 pm" src="https://cloud.githubusercontent.com/assets/1590802/20506188/44e31af0-b020-11e6-9da8-7f7f83acea0f.png">

@anandthakker if you have a cycle and want to take a look at the current state of things, that branch is the place to start. My fork of `d3-geo`, where the projection calculation is happening, is [here](https://github.com/dereklieu/d3-geo). I almost didn't have to fork `d3-geo-projection`, except it includes `d3-geo` as a dep.

**Comment by dereklieu** [comment]
A cleaner option could be to leave `d3-geo` alone and flip the projected data ourselves, or go back to using the script you already wrote. The `d3-geo-projection` CL tool is a bit cleaner on some of the weirder projections though.

**Comment by anandthakker** [comment]
Ah, cool.  I'll check out that branch -- maybe there's a nice in-between
solution; I think it would be beneficial to avoid forking the d3-* stuff if
possible.

**Comment by anandthakker** [comment]
See #6
